[package]
name = "init-tokio"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
futures = { features = ["async-await", "compat"], version = "0.3.16" }
tokio = { version = "1.10.0", default-features = false, features = ["full", "test-util"] }
