[package]
name = "cfg"
version = "0.1.0"
edition = "2018"

[dependencies]
ron = { version = "0.6.4" }
serde = { version = "1.0.126", features = ["derive"] }
chrono = { version = "0.4.19", path = "../../../contrib/lib/rust/chrono", features = ["serde"] }
sys = { version = "*", path = "../sys" }
hg-parser = { version = "0.6.0", path = "../../../contrib/lib/rust/hg-parser" }
git2 = { version = "*", path = "../../../contrib/lib/rust/git2", default-features = false }
regex = { version = "*", path = "../../../contrib/lib/rust/regex" }
