[package]
name = "flate"
version = "0.1.0"
edition = "2018"

[dependencies]
zstd = {version = "*", path = "../../../../contrib/lib/rust/zstd"}
tar = {version = "*", path = "../../../../contrib/lib/rust/tar"}
