# rlib
[package]
name = "rlib"
version = "0.1.0"
authors = ["ellis"]
edition = "2018"
resolver = "2"

[lib]
path = "lib.rs"

[workspace]
default-members = ["dts"]
members = [
  "gui",
  "dmc",
  "web",
  "cfg",
  "kala",
  "ctx",
  "db",
  "dts",
  "math",
  "net",
  "obj",
  "crypto",
  "hash",
  "flate",
  "eve",
  "audio",
  "alch",
  "logger",
  "util",
]
