[workspace]
members = [
  "gui",
  "dmc",
  "web",
  "cfg",
  "kala",
  "ctx",
  "db",
  "dts",
  "math",
  "net",
  "obj",
  "crypto",
  "hash",
  "flate",
  "eve",
  "audio",
  "alch",
  "logger",
  "util",
]

resolver = "2"
