[workspace]
members = [
  "app/email",
  "app/org",
#  "app/shed",
  "app/weather",
  "ui/gui",
#  "ui/web",
  "cfg",
  "kala",
  "ctx",
  "db",
  "dsl",
  "dts",
  "math",
  "net",
  "obj",
  "sys",
  "util",
]

resolver = "2"