[workspace]
members = [
  "app/email",
  "app/org",
  "app/shed",
  "app/weather",
  "ui/gui",
  "ui/web",
  "cfg",
  "kala",
  "ctx",
  "db",
  "dsl",
  "dts",
  "math",
  "net",
  "obj",
  "sys",
  "util",
]

resolver = "2"

[profile.release]
# less code to include into binary
panic = 'abort'
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = 'z'
# link time optimization using whole-program analysis
lto = true