# Created 2021-11-19 Fri 04:26
#+title: rlib
=rlib= is a Rust Library. It provides a loose collection of /modules/
which are conditionally compiled via [[https://doc.rust-lang.org/cargo/reference/features.html][features]]. Modules include
boiler-plate, wrappers, errors, helper functions, and some custom
interfaces.

One thing this library does *not* do is re-export an [[https://rust-lang.github.io/async-book/08_ecosystem/00_chapter.html#async-runtimes][async runtime]]. In
earlier versions it re-exported both [[https://github.com/rayon-rs/rayon][rayon]] and [[https://github.com/tokio-rs/tokio][tokio]] as a convenience
to the programmer but this has been phased out. There are however many
=async= functions available in this library, so you should come
equipped with your own runtime if you plan to =.await=.

This is a /personal/ library which is unfit for production use as it
is quite bloated, some of the individual modules are useful on their
own though.

#+results: 
| info    |                                                                                                                       |
|---------+-----------------------------------------------------------------------------------------------------------------------|
| name    | [[https://rwest.io/m#rlib][rlib]]                                                                                     |
| version | alpha-0.1                                                                                                             |
| vc      | [[https://hg.rwest.io/rlib/rev/c3465cc34930][95+:c3465cc34930]], [[https://github.com/richardwesthaver/rlib][github]] |
| updated | 26 hours ago                                                                                                          |
| lines   | 6946 = λ:6183 #:253 _:952                                                                                             |
| langs   | (Org RON Rust Text Toml)                                                                                              |
|---------+-----------------------------------------------------------------------------------------------------------------------|

* Usage
This crate is not published on crates.io. To get started you'll need
to clone the [[https://hg.rwest.io/rlib][repo]] and add it as a dependency to your project like so:
#+begin_src toml
  [package]
  name = "foo"
  #...
  [dependencies]
  rlib = { version = "0.1.0", path = "../rlib", features = ["kala","logger"]} #include some features
#+end_src

then just use the modules in your code:
#+begin_src rust
  use rlib::{logger, kala};
  use rlib::util::Result;
  fn main() {
    logger::flexi("debug").expect("logger init failed");
    println!("greetings stranger!");
    kala::cmd::sys::describe_host();
  }
#+end_src
