[source]
[source.crater]
registry = "https://github.com/richardwesthaver/crater-index"
#local-registry = "/mnt/cia/crater-rlib"

#[source.crates-io]
#replace-with = "crater"

[unstable]
multitarget = true

[doc.extern-map.registries]
crates-io = "https://docs.rs/"