#default-registry = [ "crater" ]

[registry.crater]
local = "/mnt/cia/crater_local"

[unstable]
mtime-on-use = true
timings = ["info"]
multitarget = true

[doc.extern-map.registries]
crates-io = "https://docs.rs/"