[source]
[source.crater]
#registry = "https://github.com/richardwesthaver/crater-index"
local-registry = "/mnt/cia/src/crater-local"

[source.crates-io]
replace-with = "crater"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[unstable]
multitarget = true
