[registry]
default = "crates.io"

[registries.crater]
index = "https://github.com/richardwesthaver/crater-index.git"
local-registry = "/mnt/cia/src/crater/crates"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[unstable]
multitarget = true
