[package]
name = "logger"
version = "0.1.0"
edition = "2018"

[dependencies]
log = { version = "0.4.14", features = ["kv_unstable"] }
flexi_logger = { version = "0.18.0", features = ["async", "specfile", "compress", "colors", "atty"] }