[package]
name = "obj"
version = "0.1.0"
authors = ["ellis"]
edition = "2018"
description = "Object-oriented type system"
documentation = "https://docs.rwest.io/obj"
repository = "https://hg.rwest.io/rlib"
publish = ["crater"]

[features]
default = []
full = ["vc", "org", "oauth"]
vc = ["hg", "git"]
hg = ["hg-parser"]
git = ["git2"]
org = ["orgize"]
oauth = ["yup-oauth2"]
[dependencies]
# rlib
hash = { version = "0.1.0", path = "../hash" }
logger = { version = "0.1.0", path = "../logger" }
# contrib
ron = "0.6.4"
bincode = "1.3.3"
serde_json = "1.0.66"
serde = { version = "1.0.128", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
mime = "0.3.16"
orgize = { version = "0.8.4", path = "../../orgize", optional = true }
hg-parser = { version = "0.6.0", optional = true }
git2 = { version = "0.13.20", default-features = false, optional = true }
regex = "1.5.4"
rusty_ulid = "0.11.0"
uuid = { version = "0.8", features = ["serde"] }
yup-oauth2 = { version = "5.1.0", optional = true }

# required for web frontends
[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "0.8", features = ["wasm-bindgen"] }

[dev-dependencies]
tempfile = "3.2.0"
