[package]
name = "obj"
version = "0.1.0"
edition = "2018"
description = "Object-oriented type system"

[dependencies]
# rlib
hash = { version = "0.1.0", path = "../hash" }
logger = { version = "0.1.0", path = "../logger" }
# contrib
ron = "0.6.4"
bincode = "1.3.3"
serde = { version = "1.0.128", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }

[dev-dependencies]
tempfile = "3.2.0"
