[package]
name = "obj"
version = "0.1.0"
edition = "2018"
description = "Object-oriented type system"

[dependencies]
hash = { path = "../hash" }
logger = { path = "../logger" }
ron = { version = "0.6.4" }
bincode = { version = "1.3.3" }
serde = { version = "1.0.126", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }

[dev-dependencies]
tempfile = "3.2.0"
