[package]
name = "crypto"
version = "0.1.0"
edition = "2018"

[dependencies]
ed25519-dalek = "1.0.1"
rand_core = "0.6.3"
hash = { version = "0.1.0", path = "../hash" }
ed25519 = "1.2.0"
salsa20 = { version = "0.8.1", features = ["xsalsa20"] }
x25519-dalek = "1.1.1"