[package]
name = "kala"
version = "0.1.0"
edition = "2018"

[dependencies]
cfg = { path = "../cfg" }
net = { path = "../net" }
chrono = { version = "0.4", path = "../../../contrib/lib/rust/chrono", features = ["serde"] }
ctx = { path = "../ctx" }
rusb = { version = "0.8.1", path = "../../../contrib/lib/rust/rusb" }
weather = { path = "../app/weather" }
org = { path = "../app/org" }
hash = { path = "../sys/hash" }
flate = { path = "../sys/flate" }
logger = { path = "../sys/logger" }
cmd_lib = {path = "../../../contrib/lib/rust/cmd_lib"}
ron = {path = "../../../contrib/lib/rust/ron"}
rustyline = {path = "../../../contrib/lib/rust/rustyline"}
rpassword = {path = "../../../contrib/lib/rust/rpassword"}
xrandr = {path = "../../../contrib/lib/rust/xrandr"}
tmux_interface = { version = "^0.1.0", path = "../../../contrib/lib/rust/tmux_interface", features = ["tmux_X_X"] }