[package]
name = "audio"
version = "0.1.0"
edition = "2018"

[dependencies]
cpal = { version = "0.13.3" }
dasp = { version = "0.11", path = "../../../contrib/lib/rust/dasp/dasp", features = ["all"]}
hound = { version = "3.4.0", path = "../../../contrib/lib/rust/hound" }