[package]
name = "web"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "*"
yew = "0.17.3"
console_error_panic_hook = "0.1.6"
wee_alloc = "0.4.5"
ybc = "0.1.6"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O2", "--enable-mutable-globals"]